USERNAME_REGEX = r'^[\w.@+-]+$'
USERNAME_MIN_LENGTH = 5
USERNAME_MAX_LENGTH = 32
NAME_REGEX = r'^[а-яА-ЯёЁa-zA-Z]+$'
NAME_MIN_LENGTH = 1
NAME_MAX_LENGTH = 64
SURNAME_MAX_LENGTH = 64
SURNAME_MIN_LENGHT = 1
PHONE_NUMBER = r'^[0-9]+$'
PHONE_LENGTH = 12
FAQ_MAX_LENGTH = 1024
CHAT_ID_LENGTH = 10

DATETIME_FORMAT = "%Y%m%d"
