# Generated by Django 4.2.8 on 2023-12-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='Текст вопроса')),
                ('answer', models.TextField(max_length=256, verbose_name='Текст ответа')),
                ('is_main', models.BooleanField()),
                ('is_relevant', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UniqueQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='Текст вопроса')),
                ('answer', models.TextField(blank=True, max_length=256, verbose_name='Текст ответа')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
